version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony
    ports:
      - "8000:8000"
    environment:
      APP_ENV: prod
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ativobyt_cliente_login
      MYSQL_USER: ativobyt_matheus
      MYSQL_PASSWORD: ZshHqO58]0--
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
