<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Role__CLASSMETADATA__' => 0,
'App__Entity__Login__CLASSMETADATA__' => 1,
'App__Entity__User__CLASSMETADATA__' => 2,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyInverseSideMapping')),
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Role',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RoleRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'name' => $o[1],
                        'description' => $o[2],
                        'id' => $o[3],
                        'dateCreated' => $o[4],
                        'dateUpdated' => $o[5],
                        'systemAccess' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'name' => 'name',
                        'description' => 'description',
                        'id' => 'id',
                        'date_created' => 'dateCreated',
                        'date_updated' => 'dateUpdated',
                        'system_access' => 'systemAccess',
                    ],
                ],
                'columnNames' => [
                    [
                        'name' => 'name',
                        'description' => 'description',
                        'id' => 'id',
                        'dateCreated' => 'date_created',
                        'dateUpdated' => 'date_updated',
                        'systemAccess' => 'system_access',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'role',
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_NAME' => [
                                'fields' => [
                                    'name',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'users' => $o[7],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\Role',
                ],
                'length' => [
                    1 => 100,
                    255,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'guid',
                    'datetime',
                    'datetime',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'name',
                    'description',
                    'id',
                    'dateCreated',
                    'dateUpdated',
                    'systemAccess',
                ],
                'columnName' => [
                    1 => 'name',
                    'description',
                    'id',
                    'date_created',
                    'date_updated',
                    'system_access',
                ],
                'id' => [
                    3 => true,
                ],
                'fetch' => [
                    7 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Role',
                ],
                'mappedBy' => [
                    7 => 'roles',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'users',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Login',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\LoginRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'email_userName' => $o[1],
                        'lastLoginAttempt' => $o[2],
                        'lastLoginIp' => $o[3],
                        'remember' => $o[4],
                        'id' => $o[5],
                        'dateCreated' => $o[6],
                        'dateUpdated' => $o[7],
                        'systemAccess' => $o[8],
                    ],
                ],
                'fieldNames' => [
                    [
                        'email_user_name' => 'email_userName',
                        'last_login_attempt' => 'lastLoginAttempt',
                        'last_login_ip' => 'lastLoginIp',
                        'remember' => 'remember',
                        'id' => 'id',
                        'date_created' => 'dateCreated',
                        'date_updated' => 'dateUpdated',
                        'system_access' => 'systemAccess',
                    ],
                ],
                'columnNames' => [
                    [
                        'email_userName' => 'email_user_name',
                        'lastLoginAttempt' => 'last_login_attempt',
                        'lastLoginIp' => 'last_login_ip',
                        'remember' => 'remember',
                        'id' => 'id',
                        'dateCreated' => 'date_created',
                        'dateUpdated' => 'date_updated',
                        'systemAccess' => 'system_access',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'login',
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\Login',
                ],
                'length' => [
                    1 => 50,
                    3 => 255,
                ],
                'nullable' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'string',
                    'datetime',
                    'string',
                    'boolean',
                    'guid',
                    'datetime',
                    'datetime',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'email_userName',
                    'lastLoginAttempt',
                    'lastLoginIp',
                    'remember',
                    'id',
                    'dateCreated',
                    'dateUpdated',
                    'systemAccess',
                ],
                'columnName' => [
                    1 => 'email_user_name',
                    'last_login_attempt',
                    'last_login_ip',
                    'remember',
                    'id',
                    'date_created',
                    'date_updated',
                    'system_access',
                ],
                'id' => [
                    5 => true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'fieldMappings' => [
                    [
                        'email' => $o[1],
                        'password' => $o[2],
                        'firstName' => $o[3],
                        'lastName' => $o[4],
                        'cnpjCpfRg' => $o[5],
                        'isLegalEntity' => $o[6],
                        'userName' => $o[7],
                        'twoFactorToken' => $o[8],
                        'twoFactorExpiresAt' => $o[9],
                        'isTwoFactorEnabled' => $o[10],
                        'resetPasswordToken' => $o[11],
                        'resetPasswordTokenExpiresAt' => $o[12],
                        'id' => $o[13],
                        'dateCreated' => $o[14],
                        'dateUpdated' => $o[15],
                        'systemAccess' => $o[16],
                    ],
                ],
                'fieldNames' => [
                    [
                        'email' => 'email',
                        'password' => 'password',
                        'first_name' => 'firstName',
                        'last_name' => 'lastName',
                        'cnpj_cpf_rg' => 'cnpjCpfRg',
                        'is_legal_entity' => 'isLegalEntity',
                        'user_name' => 'userName',
                        'two_factor_token' => 'twoFactorToken',
                        'two_factor_expires_at' => 'twoFactorExpiresAt',
                        'is_two_factor_enabled' => 'isTwoFactorEnabled',
                        'reset_password_token' => 'resetPasswordToken',
                        'reset_password_token_expires_at' => 'resetPasswordTokenExpiresAt',
                        'id' => 'id',
                        'date_created' => 'dateCreated',
                        'date_updated' => 'dateUpdated',
                        'system_access' => 'systemAccess',
                    ],
                ],
                'columnNames' => [
                    [
                        'email' => 'email',
                        'password' => 'password',
                        'firstName' => 'first_name',
                        'lastName' => 'last_name',
                        'cnpjCpfRg' => 'cnpj_cpf_rg',
                        'isLegalEntity' => 'is_legal_entity',
                        'userName' => 'user_name',
                        'twoFactorToken' => 'two_factor_token',
                        'twoFactorExpiresAt' => 'two_factor_expires_at',
                        'isTwoFactorEnabled' => 'is_two_factor_enabled',
                        'resetPasswordToken' => 'reset_password_token',
                        'resetPasswordTokenExpiresAt' => 'reset_password_token_expires_at',
                        'id' => 'id',
                        'dateCreated' => 'date_created',
                        'dateUpdated' => 'date_updated',
                        'systemAccess' => 'system_access',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_EMAIL' => [
                                'fields' => [
                                    'email',
                                ],
                            ],
                            'UNIQ_IDENTIFIER_USERNAME' => [
                                'fields' => [
                                    'userName',
                                ],
                            ],
                        ],
                    ],
                ],
                'associationMappings' => [
                    [
                        'roles' => $o[17],
                    ],
                ],
                'idGenerator' => [
                    $o[21],
                ],
                'name' => [
                    'App\\Entity\\User',
                    18 => 'user_roles',
                    'user_id',
                    'role_id',
                ],
                'length' => [
                    1 => 180,
                    60,
                    50,
                    50,
                    14,
                    7 => 50,
                    255,
                    11 => 255,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'string',
                    'datetime',
                    'boolean',
                    'string',
                    'datetime_immutable',
                    'guid',
                    'datetime',
                    'datetime',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'email',
                    'password',
                    'firstName',
                    'lastName',
                    'cnpjCpfRg',
                    'isLegalEntity',
                    'userName',
                    'twoFactorToken',
                    'twoFactorExpiresAt',
                    'isTwoFactorEnabled',
                    'resetPasswordToken',
                    'resetPasswordTokenExpiresAt',
                    'id',
                    'dateCreated',
                    'dateUpdated',
                    'systemAccess',
                ],
                'columnName' => [
                    1 => 'email',
                    'password',
                    'first_name',
                    'last_name',
                    'cnpj_cpf_rg',
                    'is_legal_entity',
                    'user_name',
                    'two_factor_token',
                    'two_factor_expires_at',
                    'is_two_factor_enabled',
                    'reset_password_token',
                    'reset_password_token_expires_at',
                    'id',
                    'date_created',
                    'date_updated',
                    'system_access',
                ],
                'nullable' => [
                    11 => true,
                    true,
                    19 => true,
                    true,
                ],
                'id' => [
                    13 => true,
                ],
                'cascade' => [
                    17 => [
                        'persist',
                    ],
                ],
                'fetch' => [
                    17 => 2,
                ],
                'sourceEntity' => [
                    17 => 'App\\Entity\\User',
                ],
                'inversedBy' => [
                    17 => 'users',
                ],
                'joinTable' => [
                    17 => $o[18],
                ],
                'joinTableColumns' => [
                    17 => [
                        'user_id',
                        'role_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    17 => [
                        'user_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    17 => [
                        'role_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    18 => [
                        $o[19],
                    ],
                ],
                'inverseJoinColumns' => [
                    18 => [
                        $o[20],
                    ],
                ],
                'unique' => [
                    19 => false,
                    false,
                ],
                'referencedColumnName' => [
                    19 => 'id',
                    'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    17 => 'roles',
                ],
                'targetEntity' => [
                    17 => 'App\\Entity\\Role',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
