<?php

namespace ContainerIjHn0RM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwoFactorAuthServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwoFactorAuthService' shared autowired service.
     *
     * @return \App\Service\TwoFactorAuthService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/TwoFactorAuthService.php';

        return $container->privates['App\\Service\\TwoFactorAuthService'] = new \App\Service\TwoFactorAuthService(($container->privates['security.csrf.token_generator'] ??= new \Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator()));
    }
}
