<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3rgkd8x\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3rgkd8x/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container3rgkd8x.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container3rgkd8x\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container3rgkd8x\App_KernelProdContainer([
    'container.build_hash' => '3rgkd8x',
    'container.build_id' => '22511667',
    'container.build_time' => 1737495589,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3rgkd8x');
