<?php

namespace Container3rgkd8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIZOrlvService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bIZOrlv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bIZOrlv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'role' => ['privates', 'App\\Dto\\Create\\RoleCreateDto', 'getRoleCreateDtoService', true],
        ], [
            'role' => 'App\\Dto\\Create\\RoleCreateDto',
        ]);
    }
}
