<?php

namespace Container3rgkd8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginDtoService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Dto\LoginDto' shared autowired service.
     *
     * @return \App\Dto\LoginDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/LoginDto.php';

        return $container->privates['App\\Dto\\LoginDto'] = new \App\Dto\LoginDto();
    }
}
