<?php

namespace Container3rgkd8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecoveryAccountService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Dto\RecoveryAccount' shared autowired service.
     *
     * @return \App\Dto\RecoveryAccount
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/RecoveryAccount.php';

        return $container->privates['App\\Dto\\RecoveryAccount'] = new \App\Dto\RecoveryAccount();
    }
}
