<?php

namespace ContainerEMEnNXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPingDatabaseCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\PingDatabaseCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\PingDatabaseCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:ping-database', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\PingDatabaseCommand')] fn (): \App\Command\PingDatabaseCommand => ($container->privates['App\\Command\\PingDatabaseCommand'] ?? $container->load('getPingDatabaseCommandService')));
    }
}
