<?php

namespace ContainerEMEnNXa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerconfirmPasswordResetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DfUJhC2.App\Controller\UserController::confirmPasswordReset()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DfUJhC2.App\\Controller\\UserController::confirmPasswordReset()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recovery' => ['privates', 'App\\Dto\\RecoveryAccount', 'getRecoveryAccountService', true],
        ], [
            'recovery' => 'App\\Dto\\RecoveryAccount',
        ]))->withContext('App\\Controller\\UserController::confirmPasswordReset()', $container);
    }
}
