<?php

namespace ContainerPoARrcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginControllerLoginService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.oHtiEqS.App\Controller\LoginController::Login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oHtiEqS.App\\Controller\\LoginController::Login()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'login' => ['privates', 'App\\Dto\\LoginDto', 'getLoginDtoService', true],
        ], [
            'login' => 'App\\Dto\\LoginDto',
        ]))->withContext('App\\Controller\\LoginController::Login()', $container);
    }
}
