<?php

namespace ContainerPoARrcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMapperServiceCreateService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\MapperServiceCreate' shared autowired service.
     *
     * @return \App\Service\MapperServiceCreate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MapperServiceCreate.php';

        return $container->privates['App\\Service\\MapperServiceCreate'] = new \App\Service\MapperServiceCreate();
    }
}
