<?php

namespace ContainerPoARrcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCreateDtoService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Dto\Create\UserCreateDto' shared autowired service.
     *
     * @return \App\Dto\Create\UserCreateDto
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Dto/BaseEntityDto.php';
        include_once \dirname(__DIR__, 4).'/src/Dto/Create/UserCreateDto.php';

        return $container->privates['App\\Dto\\Create\\UserCreateDto'] = new \App\Dto\Create\UserCreateDto();
    }
}
