<?php

namespace ContainerI4MWXov;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\LoginController::Login' => ['privates', '.service_locator.oHtiEqS.App\\Controller\\LoginController::Login()', 'getLoginControllerLoginService', true],
            'App\\Controller\\LoginController::recoveryAccount' => ['privates', '.service_locator.N5aefLh.App\\Controller\\LoginController::recoveryAccount()', 'getLoginControllerrecoveryAccountService', true],
            'App\\Controller\\RoleController::addRole' => ['privates', '.service_locator.bIZOrlv.App\\Controller\\RoleController::addRole()', 'getRoleControlleraddRoleService', true],
            'App\\Controller\\RoleController::updateRole' => ['privates', '.service_locator.bIZOrlv.App\\Controller\\RoleController::updateRole()', 'getRoleControllerupdateRoleService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController::validade' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::validade()', 'getUserControllervalidadeService', true],
            'App\\Controller\\UserController::update' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\LoginController:Login' => ['privates', '.service_locator.oHtiEqS.App\\Controller\\LoginController::Login()', 'getLoginControllerLoginService', true],
            'App\\Controller\\LoginController:recoveryAccount' => ['privates', '.service_locator.N5aefLh.App\\Controller\\LoginController::recoveryAccount()', 'getLoginControllerrecoveryAccountService', true],
            'App\\Controller\\RoleController:addRole' => ['privates', '.service_locator.bIZOrlv.App\\Controller\\RoleController::addRole()', 'getRoleControlleraddRoleService', true],
            'App\\Controller\\RoleController:updateRole' => ['privates', '.service_locator.bIZOrlv.App\\Controller\\RoleController::updateRole()', 'getRoleControllerupdateRoleService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::add()', 'getUserControlleraddService', true],
            'App\\Controller\\UserController:validade' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::validade()', 'getUserControllervalidadeService', true],
            'App\\Controller\\UserController:update' => ['privates', '.service_locator.R7hZWdi.App\\Controller\\UserController::update()', 'getUserControllerupdateService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LoginController::Login' => '?',
            'App\\Controller\\LoginController::recoveryAccount' => '?',
            'App\\Controller\\RoleController::addRole' => '?',
            'App\\Controller\\RoleController::updateRole' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::validade' => '?',
            'App\\Controller\\UserController::update' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LoginController:Login' => '?',
            'App\\Controller\\LoginController:recoveryAccount' => '?',
            'App\\Controller\\RoleController:addRole' => '?',
            'App\\Controller\\RoleController:updateRole' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:validade' => '?',
            'App\\Controller\\UserController:update' => '?',
        ]));
    }
}
