<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPoARrcE\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPoARrcE/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPoARrcE.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPoARrcE\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPoARrcE\App_KernelTestDebugContainer([
    'container.build_hash' => 'PoARrcE',
    'container.build_id' => '37b373e5',
    'container.build_time' => 1737495582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPoARrcE');
