<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Login extends \App\Entity\Login implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'dateCreated' => [parent::class, 'dateCreated', null],
        "\0".'*'."\0".'dateUpdated' => [parent::class, 'dateUpdated', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'systemAccess' => [parent::class, 'systemAccess', null],
        "\0".parent::class."\0".'email_userName' => [parent::class, 'email_userName', null],
        "\0".parent::class."\0".'lastLoginAttempt' => [parent::class, 'lastLoginAttempt', null],
        "\0".parent::class."\0".'lastLoginIp' => [parent::class, 'lastLoginIp', null],
        "\0".parent::class."\0".'remember' => [parent::class, 'remember', null],
        'dateCreated' => [parent::class, 'dateCreated', null],
        'dateUpdated' => [parent::class, 'dateUpdated', null],
        'email_userName' => [parent::class, 'email_userName', null],
        'id' => [parent::class, 'id', null],
        'lastLoginAttempt' => [parent::class, 'lastLoginAttempt', null],
        'lastLoginIp' => [parent::class, 'lastLoginIp', null],
        'remember' => [parent::class, 'remember', null],
        'systemAccess' => [parent::class, 'systemAccess', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
