<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'dateCreated' => [parent::class, 'dateCreated', null],
        "\0".'*'."\0".'dateUpdated' => [parent::class, 'dateUpdated', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'systemAccess' => [parent::class, 'systemAccess', null],
        "\0".parent::class."\0".'cnpjCpfRg' => [parent::class, 'cnpjCpfRg', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'isLegalEntity' => [parent::class, 'isLegalEntity', null],
        "\0".parent::class."\0".'isTwoFactorEnabled' => [parent::class, 'isTwoFactorEnabled', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'resetPasswordToken' => [parent::class, 'resetPasswordToken', null],
        "\0".parent::class."\0".'resetPasswordTokenExpiresAt' => [parent::class, 'resetPasswordTokenExpiresAt', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'twoFactorExpiresAt' => [parent::class, 'twoFactorExpiresAt', null],
        "\0".parent::class."\0".'twoFactorToken' => [parent::class, 'twoFactorToken', null],
        "\0".parent::class."\0".'userName' => [parent::class, 'userName', null],
        'cnpjCpfRg' => [parent::class, 'cnpjCpfRg', null],
        'dateCreated' => [parent::class, 'dateCreated', null],
        'dateUpdated' => [parent::class, 'dateUpdated', null],
        'email' => [parent::class, 'email', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'isLegalEntity' => [parent::class, 'isLegalEntity', null],
        'isTwoFactorEnabled' => [parent::class, 'isTwoFactorEnabled', null],
        'lastName' => [parent::class, 'lastName', null],
        'password' => [parent::class, 'password', null],
        'resetPasswordToken' => [parent::class, 'resetPasswordToken', null],
        'resetPasswordTokenExpiresAt' => [parent::class, 'resetPasswordTokenExpiresAt', null],
        'roles' => [parent::class, 'roles', null],
        'systemAccess' => [parent::class, 'systemAccess', null],
        'twoFactorExpiresAt' => [parent::class, 'twoFactorExpiresAt', null],
        'twoFactorToken' => [parent::class, 'twoFactorToken', null],
        'userName' => [parent::class, 'userName', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
